* A neovim configuration for multiple languages

This configuration is referring  LazyVim and referred dotfiles from Josh medesky, from time to time.

For those who is using multiple languages, neovim can be a good choice.
  This repository is for my workflow like below :
  - SQL with oracle databse : sqls for language server and vim-dadbod
  - Java and C++ legacy projects
  - zsh/fish/xml/html for rutine works
  - Exciting experiment projects with Rust, Json and typescripts.

Installation instruction is same as LazyVim. Start with starter kit and add your preferred plugins by copying. lua/plugins/lsp directory can be ignored but I copied it due to reference and test purposes. Codes are not cleaned up yet but it will be keep updated weekly basis.

* multiple languages?
Key binding matters for non english users like me. for example,Ctrl+space for me means changing input languages. Howver many plugins are using it with other purposes.
In language servers, key binding for code actions also mattered but seems not cared carefully yet. So, I started to make this repository to share my experiments, someday can be a common practice hopefully.



* references

- Tim Pope's vim-dadbod
 - [[https://github.com/joshmedeski/dotfiles.git][Josh medesky's dot files]]
 - LazyVim starter Kit

Dependencies:
- To be listed with homebrew listings.
- *sqls* seems not to be used with sqlfmt from homebrew. use pipx shandy-sqlfmt instead.

Caution:
- sqls were hard to configure for oracle, but found workarounds. Can be added some notes seperately later.
- Snippet related configuration needs to be revisited. Very first start makes some error but can be resumeed without issue.

* work in process
- vue and typescript for front end development with neovim
- rust and json for backend development with neovim
- sqls and vim-dadbod for database

* daily usage tips
  * searches
    * search files with telescope : space + f + f, then type file name
    * Ctrl + q to move search files to quickfix list
    * Ctrl + n/p to move quickfix list
